# **DATA PROFILING**

Import libraries:

In [11]:
import sys
!{sys.executable} -m pip install -U ydata-profiling[notebook]
!pip install jupyter-contrib-nbextensions

Requirement already satisfied: ydata-profiling[notebook] in /usr/local/lib/python3.12/dist-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling[notebook]) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (4.4.4)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (1.9.5)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (0.60.0)
Requirement already satisfied: jupyter>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (1.1.1)
Requirement already satisfied: ipywidgets>=7.5.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling[notebook]) (7.7.1)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling[notebook]) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling[notebook]) (11.3.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]) (5.7.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->ydata-profiling[notebook]) (3.0.16)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling[notebook]) (3.0.3)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter>=1.0.0->ydata-profiling[notebook]) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter>=1.0.0->ydata-profiling[notebook]) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from jupyter>=1.0.0->ydata-profiling[notebook]) (7.16.6)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/dist-packages (from jupyter>=1.0.0->ydata-profiling[notebook]) (4.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling[notebook]) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling[notebook]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling[notebook]) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling[notebook]) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling[notebook]) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling[notebook]) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling[notebook]) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling[notebook]) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling[notebook]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling[notebook]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling[notebook]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling[notebook]) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling[notebook]) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling[notebook]) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling[notebook]) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling[notebook]) (1.30)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (6.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (4.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling[notebook]) (1.17.0)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (25.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (5.9.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (5.10.4)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (2.0.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (0.23.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (1.3.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (1.5.1)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.28.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (2.14.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.2.4)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (1.4.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.8.5)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.6.1->notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (4.5.1)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.5.3)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (1.9.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (25.1.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (4.26.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (2.21.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets>=7.5.1->ydata-profiling[notebook]) (0.2.14)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert->jupyter>=1.0.0->ydata-profiling[notebook]) (2.8.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.30.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (4.0.0)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter>=1.0.0->ydata-profiling[notebook]) (0.1.1)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter>=1.0.0->ydata-profiling[notebook]) (2.0.0)

In [12]:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

In [13]:
from ydata_profiling import ProfileReport
from ydata_profiling.config import Settings
import pandas as pd
import numpy as np
import json

Import data:

In [14]:
ARTWORKS = pd.read_csv("https://raw.githubusercontent.com/omar-mohamed-azab/Polimi-Data-and-Information-Quality-Project/refs/heads/main/Dataset/artwork_data.csv")
artists = pd.read_csv("https://raw.githubusercontent.com/omar-mohamed-azab/Polimi-Data-and-Information-Quality-Project/refs/heads/main/Dataset/artist_data.csv")

/tmp/ipython-input-390809704.py:1: DtypeWarning: Columns (9,13) have mixed types. Specify dtype option on import or set low_memory=False.
  ARTWORKS = pd.read_csv("https://raw.githubusercontent.com/omar-mohamed-azab/Polimi-Data-and-Information-Quality-Project/refs/heads/main/Dataset/artwork_data.csv")

In [15]:
ARTWORKS.columns

Index(['id', 'accession_number', 'artist', 'artistRole', 'artistId', 'title',
       'dateText', 'medium', 'creditLine', 'year', 'acquisitionYear',
       'dimensions', 'width', 'height', 'depth', 'units', 'inscription',
       'thumbnailCopyright', 'thumbnailUrl', 'url'],
      dtype='object')

In [16]:
ARTWORKS.shape

(69201, 20)

In [17]:
ARTWORKS.head()

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [18]:
ARTWORKS.dtypes

id                      int64
accession_number       object
artist                 object
artistRole             object
artistId                int64
title                  object
dateText               object
medium                 object
creditLine             object
year                   object
acquisitionYear       float64
dimensions             object
width                  object
height                 object
depth                 float64
units                  object
inscription            object
thumbnailCopyright     object
thumbnailUrl           object
url                    object
dtype: object

In [19]:
config=Settings()
config.vars.text.words = False

profile = ProfileReport(ARTWORKS, title = "ARTWORKS_REPORT", config = config)

In [20]:
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/20 [00:00<?, ?it/s]
  5%|▌         | 1/20 [00:00<00:05,  3.44it/s]
 10%|█         | 2/20 [00:01<00:14,  1.22it/s]
 15%|█▌        | 3/20 [00:01<00:08,  2.00it/s]
 20%|██        | 4/20 [00:02<00:11,  1.34it/s]
 25%|██▌       | 5/20 [00:02<00:07,  1.90it/s]
 30%|███       | 6/20 [00:04<00:14,  1.02s/it]
 40%|████      | 8/20 [00:05<00:09,  1.31it/s]
 45%|████▌     | 9/20 [00:06<00:07,  1.51it/s]
 55%|█████▌    | 11/20 [00:06<00:03,  2.31it/s]
 60%|██████    | 12/20 [00:09<00:08,  1.03s/it]
 65%|██████▌   | 13/20 [00:09<00:05,  1.24it/s]
 70%|███████   | 14/20 [00:10<00:04,  1.40it/s]
 75%|███████▌  | 15/20 [00:10<00:02,  1.79it/s]
 80%|████████  | 16/20 [00:12<00:04,  1.15s/it]
 85%|████████▌ | 17/20 [00:13<00:02,  1.11it/s]
 90%|█████████ | 18/20 [00:14<00:01,  1.14it/s]
 95%|█████████▌| 19/20 [00:16<00:01,  1.41s/it]
100%|██████████| 20/20 [00:17<00:00,  1.15it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# **DATA CLEANING**

*DATA TRANSFORMATION/NORMALIZATION*

- Merging height and width into dimensions if they exist
- Uossibly removing depth (96.4% missing).
- Units has no variance, remove
- Inscription also no variance but a lot of missing values, possibly changing to dateInscription with True/False if thats the semantic, otherwise removing.
- Thumbnail copyright and thumbnail url needed? Some missing values. Picture available through the “normal” url column with 0 missing values.
- Artistrole mostly contains “Artist”, highly imbalanced.
- Possibly removing one of id and accession_number since both are unique (also Url but might be harder as an identifier). Id weirdly distributed as an argument för using accession_number as id instead.
- Year type and format needs to be addressed.
- Using artist_data for missing year, perhaps adding uncertainty column
- Making sure every artist_id, name pair is unique.
- Titles not unique, issue? Maybe not.
- Date format.
- Medium: handle missing values.

In [51]:
#Set accession_number as index
df = ARTWORKS.set_index('accession_number')
df

,id,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
accession_number,,,,,,,,,,,,,,,,,,,
A00001,1035,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
A00002,1036,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
A00003,1037,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
A00004,1038,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
A00005,1039,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T13865,122960,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305.0,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
T13866,122961,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305.0,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
T13867,121181,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410.0,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
T13868,112306,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
T13869,127035,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764–96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [52]:
# transform numeric columns
numeric_cols = ['width', 'height', 'depth', 'year']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [53]:
# Create function to merge width, height and depth into a single column if existent
def merge_dimensions(row):
    # If height or width is missing, we can't create a valid dimension
    if pd.isna(row['height']) or pd.isna(row['width']):
        return "Dimensions not known"

    # Base: Height x Width
    dim_str = f"{row['height']} x {row['width']}"

    # Add Depth only if it exists and is not 0
    if pd.notna(row['depth']) and row['depth'] > 0:
        dim_str += f" x {row['depth']}"

    return dim_str + " mm"

df['dimensions'] = df.apply(merge_dimensions, axis=1)

# Show some examples with depth and some without
print(df[['dimensions']].tail(10))

                                 dimensions
accession_number
T13860                 Dimensions not known
T13861                    1155.0 x 810.0 mm
T13862                 Dimensions not known
T13863             305.0 x 305.0 x 135.0 mm
T13864             305.0 x 305.0 x 135.0 mm
T13865             305.0 x 305.0 x 135.0 mm
T13866             305.0 x 305.0 x 135.0 mm
T13867            2410.0 x 45.0 x 2990.0 mm
T13868                 Dimensions not known
T13869                     660.0 x 508.0 mm

In [54]:
# We want to fill empty cells of 'year' with an approximation, while also representing the uncertainty in a separate variable

print("Artist Columns:", artists.columns.tolist())

# Select the correct columns (renaming them to be consistent with our logic)
artist_dates = artists[['id', 'yearOfBirth', 'yearOfDeath']].rename(
    columns={'yearOfBirth': 'birthYear', 'yearOfDeath': 'deathYear'}
)

# 2. RE-MERGE
# Merge them into the main dataframe
df = df.reset_index().merge(
    artist_dates,
    left_on='artistId',
    right_on='id',
    how='left',
    suffixes=('', '_artist_numeric')
).set_index('accession_number')

df = df.drop(columns=['id_artist_numeric'], errors='ignore')

# Define approximation logic
def estimate_year_logic(row):
    # Case A: We already have a valid year -> "Verified"
    if pd.notna(row['year']):
        return pd.Series([row['year'], "Verified", f"{int(row['year'])}"])

    # Case B: Missing year, but we have Artist Birth/Death
    if pd.notna(row['birthYear']) and pd.notna(row['deathYear']):
        # Assumption: Artist starts working at age 20
        start_career = row['birthYear'] + 20
        end_career = row['deathYear']

        # Check validity (sometimes death is missing or invalid)
        if end_career > start_career:
            mid_point = start_career + (end_career - start_career) / 2
            label = f"c. {int(start_career)}–{int(end_career)} (Artist Era)"
            return pd.Series([int(mid_point), "Estimated", label])

    # Case C: No data at all -> Remain Missing
    return pd.Series([np.nan, "Unknown", "Date not known"])

print("Calculating estimates for missing years...")
df[['year_numeric', 'year_certainty', 'date_display']] = df.apply(estimate_year_logic, axis=1)

estimated_mask = df['year_certainty'] == 'Estimated'

print(df[estimated_mask][['artist','year_numeric', 'year_certainty', 'date_display']].sample(10))

Artist Columns: ['id', 'name', 'gender', 'dates', 'yearOfBirth', 'yearOfDeath', 'placeOfBirth', 'placeOfDeath', 'url']
Calculating estimates for missing years...
                                          artist  year_numeric year_certainty  \
accession_number
A01378                             Jones, George        1837.0      Estimated
D36671            Turner, Joseph Mallord William        1823.0      Estimated
D36664            Turner, Joseph Mallord William        1823.0      Estimated
T08169                               Kinnard, W.        1827.0      Estimated
T08582                              Barry, James        1783.0      Estimated
N02047                           Stevens, Alfred        1856.0      Estimated
A01601                             Jones, George        1837.0      Estimated
A01579                             Jones, George        1837.0      Estimated
A00549                             Jones, George        1837.0      Estimated
D40176            Turner, Joseph Mallord William        1823.0      Estimated

                               date_display
accession_number
A01378            c. 1806–1869 (Artist Era)
D36671            c. 1795–1851 (Artist Era)
D36664            c. 1795–1851 (Artist Era)
T08169            c. 1827–1828 (Artist Era)
T08582            c. 1761–1806 (Artist Era)
N02047            c. 1837–1875 (Artist Era)
A01601            c. 1806–1869 (Artist Era)
A01579            c. 1806–1869 (Artist Era)
A00549            c. 1806–1869 (Artist Era)
D40176            c. 1795–1851 (Artist Era)

In [55]:
top_titles = df['title'].value_counts().head(20)
print(top_titles)

title
[title not known]                                3572
Blank                                            3031
[blank]                                          2482
[no title]                                       1874
Untitled                                          639
Mountains                                         538
[inscriptions by Turner]                          209
Shipping                                          202
Buildings                                         156
River Scene                                       109
Study of Sky                                      101
Printed Page of Coltman’s ‘British Itinerary’      92
Inscription by Turner: Draft of Poetry             81
Coast Scene                                        73
Cliffs                                             69
Landscape                                          67
Castle on Rock                                     67
[inscription by Turner]                            66
Sketches                                           61
On Coast                                           58
Name: count, dtype: int64

In [56]:
# clean 'Untitled' variations and inscriptions
untitled_variants = [
    '[title not known]',
    'Blank',
    '[blank]',
    '[no title]'
]

df['title_cleaned'] = df['title'].replace(untitled_variants, 'Untitled')

mask_inscription = df['title_cleaned'].str.contains(r'inscription', case=False, regex=True)
df.loc[mask_inscription, 'title_cleaned'] = 'Inscription (Various)'
print(df['title_cleaned'].value_counts().head(10))

title_cleaned
Untitled                                         11598
Inscription (Various)                             1268
Mountains                                          538
Shipping                                           202
Buildings                                          156
River Scene                                        109
Study of Sky                                       101
Printed Page of Coltman’s ‘British Itinerary’       92
Coast Scene                                         73
Cliffs                                              69
Name: count, dtype: int64

In [57]:
# check for name variations for artistID
name_counts = df.groupby('artistId')['artist'].nunique()
inconsistent_ids = name_counts[name_counts > 1]
inconsistent_ids

Series([], Name: artist, dtype: int64)

In [58]:
# Check for inconsistencies between names and id pairs in artworks and artist dataset
official_names = artists.set_index('id')['name']
mask_mismatch = (
    df['artistId'].isin(official_names.index) &
    (df['artist'].str.strip() != df['artistId'].map(official_names).str.strip())
)

mismatches = df[mask_mismatch]
mismatches

Empty DataFrame
Columns: [id, artist, artistRole, artistId, title, dateText, medium, creditLine, year, acquisitionYear, dimensions, width, height, depth, units, inscription, thumbnailCopyright, thumbnailUrl, url, birthYear, deathYear, year_numeric, year_certainty, date_display, title_cleaned]
Index: []

[0 rows x 25 columns]

In [59]:
# Check medium variation
top_mediums = df['medium'].value_counts().head(50)
print(top_mediums)

medium
Graphite on paper                                  26167
Oil paint on canvas                                 3383
Screenprint on paper                                2984
Lithograph on paper                                 2721
Watercolour on paper                                1890
Etching on paper                                    1793
Graphite and watercolour on paper                   1680
Ink on paper                                         880
Intaglio print on paper                              820
Photograph, gelatin silver print on paper            750
Engraving on paper                                   732
Line engraving on paper                              645
Chalk and graphite on paper                          619
Pen and ink on paper                                 598
Chalk on paper                                       526
Gouache and watercolour on paper                     475
Print on paper                                       435
Aquatint on paper                                    412
Ink and graphite on paper                            409
Etching and aquatint on paper                        394
Ink and watercolour on paper                         384
Bronze                                               384
Wood engraving on paper                              345
Gouache, graphite and watercolour on paper           321
Copper plate                                         319
Mezzotint on paper                                   269
Digital print on paper                               264
Graphite and ink on paper                            263
Oil paint on wood                                    247
Graphite, ink and watercolour on paper               245
Oil paint on board                                   224
Watercolour and graphite on paper                    222
Gouache and graphite on paper                        206
Acrylic paint on canvas                              162
Woodcut on paper                                     161
Photograph, gelatine silver print on paper           152
Pen and ink and graphite on paper                    148
Graphite and chalk on paper                          144
Drypoint on paper                                    134
Pastel on paper                                      129
Graphite, watercolour and ink on paper               126
Photograph, colour, Chromogenic print, on paper      116
Watercolour and gouache on paper                     112
Linocut on paper                                     110
Etching and engraving on paper                       109
Graphite on paper. Verso: graphite on paper          109
Etching and watercolour on paper                     108
Engraving and etching on paper                       106
Watercolour and ink on paper                         106
Graphite, watercolour and gouache on paper           106
Name: count, dtype: int64

In [60]:
# Make new boolean column 'has_inscription' to replace 'inscription'
if 'inscription' in df.columns:
    df['has_inscription'] = df['inscription'].notna()

In [61]:
# Fill empty cells for creditLine, medium and thumbnailCopyright
df['creditLine'] = df['creditLine'].fillna("No credit line recorded")
df['medium'] = df['medium'].fillna("Unknown Medium")
df['thumbnailCopyright'] = df['thumbnailCopyright'].fillna("No copyright information available")
df['thumbnailUrl'] = df['thumbnailUrl'].fillna("No thumbnail URL available")

In [62]:
# Lets group the different mediums into larger groups
def clean_medium(text):
    # Convert to string and lowercase to avoid case issues
    text = str(text).lower()

    # Modern/New Media
    if any(x in text for x in ['video', 'film', 'audio', 'digital', 'screenprint', 'photograph', 'c-print', 'plastic', 'acrylic', 'installation']):
        return 'Modern Media'

    # Sculptures (3D Materials)
    if any(x in text for x in ['bronze', 'marble', 'stone', 'plaster', 'sculpture', 'metal', 'steel', 'wood', 'glass']):
        return 'Sculpture'

    # Paintings (Traditional)
    if any(x in text for x in ['oil', 'canvas', 'tempera', 'panel', 'paint', 'gouache']):
        return 'Painting'

    # Works on Paper (Drawings, Prints)
    if any(x in text for x in ['paper', 'ink', 'graphite', 'watercolour', 'chalk', 'pencil', 'print', 'etching', 'engraving', 'lithograph']):
        return 'Work on Paper'

    # Everything else
    return 'Other/Unknown'

df['medium_group'] = df['medium'].apply(clean_medium)


# Compare the mess of the original vs the clean version
print("--- Before (Top 5 Raw) ---")
print(df['medium'].value_counts().head(5))

print("\n--- After (Clean Categories) ---")
print(df['medium_group'].value_counts())

--- Before (Top 5 Raw) ---
medium
Graphite on paper       26167
Unknown Medium           6384
Oil paint on canvas      3383
Screenprint on paper     2984
Lithograph on paper      2721
Name: count, dtype: int64

--- After (Clean Categories) ---
medium_group
Work on Paper    46438
Other/Unknown     7072
Painting          6603
Modern Media      6510
Sculpture         2578
Name: count, dtype: int64

In [63]:
df.columns

Index(['id', 'artist', 'artistRole', 'artistId', 'title', 'dateText', 'medium',
       'creditLine', 'year', 'acquisitionYear', 'dimensions', 'width',
       'height', 'depth', 'units', 'inscription', 'thumbnailCopyright',
       'thumbnailUrl', 'url', 'birthYear', 'deathYear', 'year_numeric',
       'year_certainty', 'date_display', 'title_cleaned', 'has_inscription',
       'medium_group'],
      dtype='object')

In [64]:
# Drop columns
cols_to_drop = [
    'id',               # Redundant (using accession_number)
    'artistRole',       # Imbalanced, non-informative
    'width',            # Displayed in dimensions
    'height',           # Displayed in dimensions
    'depth',            # High missing values
    'units',            # No variance, information alreadt in 'dimensions'
    'inscription',      # Replaced by 'has_inscription'
    'birthYear',        # Already used for computation, redundant
    'deathYear',        # Already used for computation, redundant
    'year',              # Replaced by year_numeric
    'birthYear_artist_numeric',
    'deathYear_artist_numeric',
    'title',             # Replaced by 'title_cleaned'
    'dateText'
]

In [65]:
# Rename
df = df.drop(columns=cols_to_drop, errors='ignore')
df = df.rename(columns={'year_numeric': 'year', 'title_cleaned': 'title'})

In [66]:
df.columns

Index(['artist', 'artistId', 'medium', 'creditLine', 'acquisitionYear',
       'dimensions', 'thumbnailCopyright', 'thumbnailUrl', 'url', 'year',
       'year_certainty', 'date_display', 'title', 'has_inscription',
       'medium_group'],
      dtype='object')

In [67]:
# Re-order columns
df = df[['artist', 'artistId','title', 'medium', 'medium_group', 'creditLine', 'year','year_certainty',
         'acquisitionYear', 'dimensions', 'date_display', 'has_inscription', 'thumbnailCopyright', 'thumbnailUrl', 'url']]

In [68]:
df.columns

Index(['artist', 'artistId', 'title', 'medium', 'medium_group', 'creditLine',
       'year', 'year_certainty', 'acquisitionYear', 'dimensions',
       'date_display', 'has_inscription', 'thumbnailCopyright', 'thumbnailUrl',
       'url'],
      dtype='object')

In [69]:
df.dtypes

artist                 object
artistId                int64
title                  object
medium                 object
medium_group           object
creditLine             object
year                  float64
year_certainty         object
acquisitionYear       float64
dimensions             object
date_display           object
has_inscription          bool
thumbnailCopyright     object
thumbnailUrl           object
url                    object
dtype: object

In [70]:
df

,artist,artistId,title,medium,medium_group,creditLine,year,year_certainty,acquisitionYear,dimensions,date_display,has_inscription,thumbnailCopyright,thumbnailUrl,url
accession_number,,,,,,,,,,,,,,,
A00001,"Blake, Robert",38,A Figure Bowing before a Seated Old Man with h...,"Watercolour, ink, chalk and graphite on paper....",Work on Paper,Presented by Mrs John Richmond 1922,1784.0,Estimated,1922.0,419.0 x 394.0 mm,c. 1782–1787 (Artist Era),False,No copyright information available,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
A00002,"Blake, Robert",38,"Two Drawings of Frightened Figures, Probably f...",Graphite on paper,Work on Paper,Presented by Mrs John Richmond 1922,1784.0,Estimated,1922.0,213.0 x 311.0 mm,c. 1782–1787 (Artist Era),False,No copyright information available,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
A00003,"Blake, Robert",38,The Preaching of Warning. Verso: An Old Man En...,Graphite on paper. Verso: graphite on paper,Work on Paper,Presented by Mrs John Richmond 1922,1785.0,Verified,1922.0,467.0 x 343.0 mm,1785,False,No copyright information available,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
A00004,"Blake, Robert",38,Six Drawings of Figures with Outstretched Arms,Graphite on paper,Work on Paper,Presented by Mrs John Richmond 1922,1784.0,Estimated,1922.0,394.0 x 318.0 mm,c. 1782–1787 (Artist Era),False,No copyright information available,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
A00005,"Blake, William",39,The Circle of the Lustful: Francesca da Rimini...,Line engraving on paper,Work on Paper,Purchased with the assistance of a special gra...,1826.0,Verified,1919.0,335.0 x 243.0 mm,1826,False,No copyright information available,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T13865,"P-Orridge, Genesis",16646,Larvae (from Tampax Romana),"Perspex, Wood, hairpiece, tampon and human blood",Sculpture,Transferred from Tate Archive 2012,1975.0,Verified,2013.0,305.0 x 305.0 x 135.0 mm,1975,False,No copyright information available,No thumbnail URL available,http://www.tate.org.uk/art/artworks/p-orridge-...
T13866,"P-Orridge, Genesis",16646,Living Womb (from Tampax Romana),"Wood, Perspex, plastic, photograph on paper, t...",Modern Media,Transferred from Tate Archive 2012,1976.0,Verified,2013.0,305.0 x 305.0 x 135.0 mm,1976,False,No copyright information available,No thumbnail URL available,http://www.tate.org.uk/art/artworks/p-orridge-...
T13867,"Hatoum, Mona",2365,Present Tense,Soap and glass beads,Sculpture,Presented by Tate Members 2013,1996.0,Verified,2013.0,2410.0 x 45.0 x 2990.0 mm,1996,False,No copyright information available,No thumbnail URL available,http://www.tate.org.uk/art/artworks/hatoum-pre...
T13868,"Creed, Martin",2760,Work No. 227: The lights going on and off,Gallery lighting,Other/Unknown,"Purchased with funds provided by Tate Members,...",2000.0,Verified,2013.0,Dimensions not known,2000,False,No copyright information available,No thumbnail URL available,http://www.tate.org.uk/art/artworks/creed-work...
T13869,"Brunias, Agostino",3824,Dancing Scene in the West Indies,Oil paint on canvas,Painting,Purchased with assistance from Tate Patrons an...,1764.0,Verified,2013.0,660.0 x 508.0 mm,1764,False,No copyright information available,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [41]:
profile_cleaned = ProfileReport(df, title = "ARTWORKS_CLEAN_REPORT", config = config)

In [42]:
profile_cleaned

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]
  7%|▋         | 1/15 [00:00<00:02,  6.39it/s]
 20%|██        | 3/15 [00:01<00:05,  2.27it/s]
 47%|████▋     | 7/15 [00:01<00:01,  5.69it/s]
 67%|██████▋   | 10/15 [00:02<00:01,  4.62it/s]
 87%|████████▋ | 13/15 [00:02<00:00,  5.61it/s]
 93%|█████████▎| 14/15 [00:03<00:00,  2.89it/s]
100%|██████████| 15/15 [00:04<00:00,  3.28it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [43]:
from google.colab import files

# 1. Save the dataframe to a CSV file in the Colab environment
# We use index=True to keep the 'accession_number' which is currently your index
df.to_csv('tate_artwork_cleaned.csv', index=True)

print("File saved to Colab. Starting download...")

# 2. Trigger the browser to download the file to your computer
files.download('tate_artwork_cleaned.csv')

File saved to Colab. Starting download...