# **1. Data Quality Assesment**

In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
from datetime import datetime
import os
import pprint

In [ ]:
# Reading the dataset
artwork_data = pd.read_csv('https://raw.githubusercontent.com/omar-mohamed-azab/Polimi-Data-and-Information-Quality-Project/refs/heads/main/Dataset/artwork_data.csv')
artist_data = pd.read_csv('https://raw.githubusercontent.com/omar-mohamed-azab/Polimi-Data-and-Information-Quality-Project/refs/heads/main/Dataset/artist_data.csv')

/tmp/ipython-input-3758514550.py:2: DtypeWarning: Columns (9,13) have mixed types. Specify dtype option on import or set low_memory=False.
  artwork_data = pd.read_csv('https://raw.githubusercontent.com/omar-mohamed-azab/Polimi-Data-and-Information-Quality-Project/refs/heads/main/Dataset/artwork_data.csv')

In [ ]:
artwork_data

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305.0,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305.0,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410.0,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764–96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660.0,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [ ]:
artist_data

,id,name,gender,dates,yearOfBirth,yearOfDeath,placeOfBirth,placeOfDeath,url
0,10093,"Abakanowicz, Magdalena",Female,born 1930,1930.0,NaN,Polska,NaN,http://www.tate.org.uk/art/artists/magdalena-a...
1,0,"Abbey, Edwin Austin",Male,1852–1911,1852.0,1911.0,"Philadelphia, United States","London, United Kingdom",http://www.tate.org.uk/art/artists/edwin-austi...
2,2756,"Abbott, Berenice",Female,1898–1991,1898.0,1991.0,"Springfield, United States","Monson, United States",http://www.tate.org.uk/art/artists/berenice-ab...
3,1,"Abbott, Lemuel Francis",Male,1760–1803,1760.0,1803.0,"Leicestershire, United Kingdom","London, United Kingdom",http://www.tate.org.uk/art/artists/lemuel-fran...
4,622,"Abrahams, Ivor",Male,born 1935,1935.0,NaN,"Wigan, United Kingdom",NaN,http://www.tate.org.uk/art/artists/ivor-abraha...
...,...,...,...,...,...,...,...,...,...
3527,12542,"Zorio, Gilberto",Male,born 1944,1944.0,NaN,"Andorno Micca, Italia",NaN,http://www.tate.org.uk/art/artists/gilberto-zo...
3528,2186,"Zox, Larry",Male,born 1936,1936.0,NaN,"Des Moines, United States",NaN,http://www.tate.org.uk/art/artists/larry-zox-2186
3529,621,"Zuccarelli, Francesco",Male,1702–1788,1702.0,1788.0,Italia,Firenze,http://www.tate.org.uk/art/artists/francesco-z...
3530,2187,"Zuloaga, Ignacio",Male,1870–1945,1870.0,1945.0,España,España,http://www.tate.org.uk/art/artists/ignacio-zul...
3531,2188,"Zyw, Aleksander",Male,1905–1995,1905.0,1995.0,Polska,NaN,http://www.tate.org.uk/art/artists/aleksander-...

In [ ]:
# Printing the dimesnsions of the data
print('dimensions of artwork data:', artwork_data.shape)
print('dimensions of artist data:', artist_data.shape)

dimensions of artwork data: (69201, 20)
dimensions of artist data: (3532, 9)

In [ ]:
# Showing the type of columns
artwork_data.dtypes

id                      int64
accession_number       object
artist                 object
artistRole             object
artistId                int64
title                  object
dateText               object
medium                 object
creditLine             object
year                   object
acquisitionYear       float64
dimensions             object
width                  object
height                 object
depth                 float64
units                  object
inscription            object
thumbnailCopyright     object
thumbnailUrl           object
url                    object
dtype: object

In [ ]:
# Checking for duplicates
artwork_data.duplicated().any()

np.False_

In [ ]:
# Checking null values
artwork_data.isnull()

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,True,False,False
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
69197,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
69198,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False
69199,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,False
69200,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,False,False

In [ ]:
# Check the number of null values in each column
artwork_data.isnull().sum()

id                        0
accession_number          0
artist                    0
artistRole                0
artistId                  0
title                     0
dateText                  0
medium                 6384
creditLine                3
year                   5378
acquisitionYear          45
dimensions             2433
width                  3341
height                 3341
depth                 66687
units                  3341
inscription           62895
thumbnailCopyright    54962
thumbnailUrl          10786
url                       0
dtype: int64

In [ ]:
# Number of nit Null values in each column
artwork_data.notnull().sum()

id                    69201
accession_number      69201
artist                69201
artistRole            69201
artistId              69201
title                 69201
dateText              69201
medium                62817
creditLine            69198
year                  63823
acquisitionYear       69156
dimensions            66768
width                 65860
height                65860
depth                  2514
units                 65860
inscription            6306
thumbnailCopyright    14239
thumbnailUrl          58415
url                   69201
dtype: int64

In [ ]:
# Total number of Nulls in the data
artwork_data.isnull().sum().sum()

np.int64(219596)

In [ ]:
# Total number of cells that are not Null
Not_Null = artwork_data.notnull().sum().sum()
Not_Null

np.int64(1164424)

In [ ]:
# Total number of cells in the data
TOT = artwork_data.shape[0]*artwork_data.shape[1]
TOT

1384020

In [ ]:
# Evaluating Completeness
Completeness = Not_Null/TOT
Completeness = '{0:.1f}%'.format(Completeness*100)
print(Completeness)

84.1%